function J_theta_leg = Jacob_theta_leg(T_base, T_tool, q_active, q_passive, thetas, link)

T_leg = T_base * (Tz(q_active) * Tz(thetas(1)) * Rz(q_passive(1)) * Tx(link(1)) * ( Tx(thetas(2))*Ty(thetas(3))*Tz(thetas(4))*Rx(thetas(5))*Ry(thetas(6))*Rz(thetas(7)) ) * Rz(q_passive(2)) * Tx(link(2)) * ( Tx(thetas(8))*Ty(thetas(9))*Tz(thetas(10))*Rx(thetas(11))*Ry(thetas(12))*Rz(thetas(13)) ) * Rz(q_passive(3)) ) * T_tool;

% theta1
T_dtheta1 = Tz(q_active)    * Tzd(thetas(1))   * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta1 = T_base * T_dtheta1 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;

J_theta_leg(1:6,1) = [T_FK_dtheta1(1,4) ; T_FK_dtheta1(2,4) ; T_FK_dtheta1(3,4) ; T_FK_dtheta1(3,2) ; T_FK_dtheta1(1,3) ; T_FK_dtheta1(2,1)];
 
% theta2
T_dtheta2 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Txd(thetas(2))   * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta2 = T_base * T_dtheta2 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,2) = [T_FK_dtheta2(1,4) ; T_FK_dtheta2(2,4) ; T_FK_dtheta2(3,4) ; T_FK_dtheta2(3,2) ; T_FK_dtheta2(1,3) ; T_FK_dtheta2(2,1)];

% theta3
T_dtheta3 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Tyd(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta3 = T_base * T_dtheta3 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,3) = [T_FK_dtheta3(1,4) ; T_FK_dtheta3(2,4) ; T_FK_dtheta3(3,4) ; T_FK_dtheta3(3,2) ; T_FK_dtheta3(1,3) ; T_FK_dtheta3(2,1)];

% theta4
T_dtheta4 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tzd(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta4 = T_base * T_dtheta4 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,4) = [T_FK_dtheta4(1,4) ; T_FK_dtheta4(2,4) ; T_FK_dtheta4(3,4) ; T_FK_dtheta4(3,2) ; T_FK_dtheta4(1,3) ; T_FK_dtheta4(2,1)];

% theta5
T_dtheta5 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tz(thetas(4)) * Rxd(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta5 = T_base * T_dtheta5 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,5) = [T_FK_dtheta5(1,4) ; T_FK_dtheta5(2,4) ; T_FK_dtheta5(3,4) ; T_FK_dtheta5(3,2) ; T_FK_dtheta5(1,3) ; T_FK_dtheta5(2,1)];

% theta6
T_dtheta6 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ryd(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta6 = T_base * T_dtheta6 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,6) = [T_FK_dtheta6(1,4) ; T_FK_dtheta6(2,4) ; T_FK_dtheta6(3,4) ; T_FK_dtheta6(3,2) ; T_FK_dtheta6(1,3) ; T_FK_dtheta6(2,1)];

% theta7
T_dtheta7 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rzd(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta7 = T_base * T_dtheta7 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,7) = [T_FK_dtheta7(1,4) ; T_FK_dtheta7(2,4) ; T_FK_dtheta7(3,4) ; T_FK_dtheta7(3,2) ; T_FK_dtheta7(1,3) ; T_FK_dtheta7(2,1)];

% theta8
T_dtheta8 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Txd(thetas(8))   * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta8 = T_base * T_dtheta8 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,8) = [T_FK_dtheta8(1,4) ; T_FK_dtheta8(2,4) ; T_FK_dtheta8(3,4) ; T_FK_dtheta8(3,2) ; T_FK_dtheta8(1,3) ; T_FK_dtheta8(2,1)];

% theta9
T_dtheta9 = Tz(q_active)    * Tz(thetas(1))    * ...
            Rz(q_passive(1))* ...
            Tx(link(1))     * Tx(thetas(2))    * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
            Rz(q_passive(2))* ...
            Tx(link(2))     * Tx(thetas(8))    * Tyd(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
            Rz(q_passive(3)) ...
            ;
        
T_FK_dtheta9 = T_base * T_dtheta9 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,9) = [T_FK_dtheta9(1,4) ; T_FK_dtheta9(2,4) ; T_FK_dtheta9(3,4) ; T_FK_dtheta9(3,2) ; T_FK_dtheta9(1,3) ; T_FK_dtheta9(2,1)];

% theta10
T_dtheta10 = Tz(q_active)   * Tz(thetas(1))    * ...
             Rz(q_passive(1))* ...
             Tx(link(1))     * Tx(thetas(2))   * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
             Rz(q_passive(2))* ...
             Tx(link(2))     * Tx(thetas(8))   * Ty(thetas(9)) * Tzd(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
             Rz(q_passive(3)) ...
             ;
        
T_FK_dtheta10 = T_base * T_dtheta10 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,10) = [T_FK_dtheta10(1,4) ; T_FK_dtheta10(2,4) ; T_FK_dtheta10(3,4) ; T_FK_dtheta10(3,2) ; T_FK_dtheta10(1,3) ; T_FK_dtheta10(2,1)];

% theta11
T_dtheta11 = Tz(q_active)   * Tz(thetas(1))    * ...
             Rz(q_passive(1))* ...
             Tx(link(1))     * Tx(thetas(2))   * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
             Rz(q_passive(2))* ...
             Tx(link(2))     * Tx(thetas(8))   * Ty(thetas(9)) * Tz(thetas(10)) * Rxd(thetas(11)) * Ry(thetas(12)) * Rz(thetas(13)) * ...
             Rz(q_passive(3)) ...
             ;
        
T_FK_dtheta11 = T_base * T_dtheta11 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,11) = [T_FK_dtheta11(1,4) ; T_FK_dtheta11(2,4) ; T_FK_dtheta11(3,4) ; T_FK_dtheta11(3,2) ; T_FK_dtheta11(1,3) ; T_FK_dtheta11(2,1)];

% theta12
T_dtheta12 = Tz(q_active)   * Tz(thetas(1))    * ...
             Rz(q_passive(1))* ...
             Tx(link(1))     * Tx(thetas(2))   * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
             Rz(q_passive(2))* ...
             Tx(link(2))     * Tx(thetas(8))   * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ryd(thetas(12)) * Rz(thetas(13)) * ...
             Rz(q_passive(3)) ...
             ;
        
T_FK_dtheta12 = T_base * T_dtheta12 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,12) = [T_FK_dtheta12(1,4) ; T_FK_dtheta12(2,4) ; T_FK_dtheta12(3,4) ; T_FK_dtheta12(3,2) ; T_FK_dtheta12(1,3) ; T_FK_dtheta12(2,1)];

% theta13
T_dtheta13 = Tz(q_active)   * Tz(thetas(1))    * ...
             Rz(q_passive(1))* ...
             Tx(link(1))     * Tx(thetas(2))   * Ty(thetas(3)) * Tz(thetas(4)) * Rx(thetas(5)) * Ry(thetas(6)) * Rz(thetas(7)) * ...
             Rz(q_passive(2))* ...
             Tx(link(2))     * Tx(thetas(8))   * Ty(thetas(9)) * Tz(thetas(10)) * Rx(thetas(11)) * Ry(thetas(12)) * Rzd(thetas(13)) * ...
             Rz(q_passive(3)) ...
             ;
        
T_FK_dtheta13 = T_base * T_dtheta13 * [inv(T_leg(1:3,1:3)) zeros(3,1); 0 0 0 1] * T_tool ;
J_theta_leg(1:6,13) = [T_FK_dtheta13(1,4) ; T_FK_dtheta13(2,4) ; T_FK_dtheta13(3,4) ; T_FK_dtheta13(3,2) ; T_FK_dtheta13(1,3) ; T_FK_dtheta13(2,1)];

end 